#!/usr/bin/env bash
#
# Script to manage the lifecycle of this configuration module.
# Run it without arguments for further information.

MODULE=vifm

function INSTALL() {
    link $CURRENT_DIRECTORY ~/.${MODULE} 
}

############################################################## begin-bootstrap
function _bootstrap() {
    CURRENT_DIRECTORY=$(dirname $(readlink -e $0))
    local _libDirectory=configuration-module-lib
    local _template=$CURRENT_DIRECTORY/$_libDirectory/management-template.sh
    command -v git &>/dev/null && {
        cd $CURRENT_DIRECTORY
        git submodule --quiet update --init $_libDirectory
        [ -e $_template ] && source $_template $@
    }
    echo "Bootstrap operation failed. Aborting."; exit 1
}
_bootstrap $@
############################################################## end-bootstrap
